version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: your_token
      INFLUX_ORG: your_org
      INFLUX_BUCKET: your_bucket
      MYSQL_HOST: mariadb
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: userdb
    depends_on:
      - influxdb
      - mariadb

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: your_org
      DOCKER_INFLUXDB_INIT_BUCKET: your_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: your_token

  mariadb:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: userdb
      MYSQL_USER: youruser
      MYSQL_PASSWORD: yourpassword
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  influxdb:
  mariadb:
